### ISSUE TITLE
I try to compile the game, but I keep getting, "Class<webm.WebmPlayer> has no field SKIP_STEP_LIMIT"

### ISSUE THREAD

**Issue by MeapMike** [KadeArchive/Kade-Engine#1059] opened 2021-06-27 06:02 UTC
![image](https://user-images.githubusercontent.com/84756874/123534724-c0c5ad00-d6e4-11eb-834b-edd043d7368a.png)
This isn't really a bug, but I would like some help with this.

**Comment by ACardboardBox1** [comment] 2021-06-27 14:01
possible duplicate of #1057 ??

**Comment by Raltyro** [comment] 2021-06-27 14:19
> possible duplicate of #1057 ??

Nope,
This issue is related to compiling, not when during ingame

also i fixed this issue by just replacing backgroundVideo function with something, i forgot what was it.

**Comment by ACardboardBox1** [comment] 2021-06-27 14:28
> 
> 
> > possible duplicate of #1057 ??
> 
> Nope,
> This issue is related to compiling, not when during ingame
> 
> also i fixed this issue by just replacing backgroundVideo function with something, i forgot what was it.

try checking your kade engine if you want to remember

**Closed as completed** 2021-10-17 19:20 UTC
Labels: bug
