### ISSUE TITLE
error compiling kade engine master

### ISSUE THREAD

**Issue by xLuigiGamerx** [KadeArchive/Kade-Engine#1873] opened 2021-08-21 15:18 UTC
i tried compiling kade engine master the latest and I got this message and it didnt compile:
source/LuaClass.hx:33: characters 46-58 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:581: characters 40-52 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:312: characters 42-54 : Type not found : StatePointer
source/Replay.hx:55: lines 55-145 : Defined in this class
source/LuaClass.hx:423: characters 7-14 : LuaClass does not have a constructor
source/LuaClass.hx:430: characters 7-16 : Unknown identifier : className
source/LuaClass.hx:439: characters 19-33 : Unknown identifier : SetNumProperty
source/ModchartState.hx:639: characters 46-54 : LuaReceptor has no field Register
source/ModchartState.hx:642: characters 5-54 : LuaCamera does not have a constructor
source/ModchartState.hx:643: characters 5-58 : LuaCamera does not have a constructor
source/ModchartState.hx:644: characters 5-64 : LuaCamera does not have a constructor
source/LuaClass.hx:149: characters 7-14 : LuaClass does not have a constructor
source/LuaClass.hx:150: characters 7-16 : Unknown identifier : className
source/LuaClass.hx:161: characters 19-33 : Unknown identifier : SetNumProperty
source/PlayState.hx:2233: characters 44-52 : LuaNote has no field Register

**Comment by cah-keith-baker01** [comment] 2021-08-21 15:47
Duplicate of #1850

**Closed as completed** 2021-08-22 10:33 UTC
Labels: bug
